name: osiris_query_2
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  # sql
  - sqlalchemy
  - oracledb
  - pyodbc
  - sqlparse
  # scheduling
  - schedule
  # data
  - lxml
  - pandas
  - pyarrow
  - tabulate
  # visualization
  - altair
  - matplotlib
  # io
  - xlrd
  - xlsxwriter
  - openpyxl
  # interaction
  - jupyter
  - jupyterlab
  - ipykernel
  - flask
  # templating
  - jinja2
  - markdown
  # statistics
  - scipy
  - scikit-learn
  - statsmodels
  - pymc
