[paths]
schema = "./schema"
queries = "./definitions"
templates = "./templates"
output = "."
tasks = "."

[credentials]
db1 = "~/credentials/db1.ini"

[defaults]

[defaults.aggregation]
label_totals = "Total"
label_na = "<NA>"
